apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-app-deployment
  labels:
    app: support-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-app
  template:
    metadata:
      labels:
        app: support-app
    spec:
      containers:
      - name: support-app
        # Reemplaza con tu imagen real del ACR
        image: acrcarlos69lmv8.azurecr.io/support-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: "sqladmin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: password
        - name: DB_SERVER
          value: "sqlserver-carlos-lab.database.windows.net"
        - name: DB_NAME
          value: "SupportDB"
        - name: PORT
          value: "3000"