apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Esto limpia el prefijo /tickets para que la app vea la raíz /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  output:
  - http:
      paths:
      - path: /tickets(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: support-app-service
            port:
              number: 80