apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Eliminamos el rewrite-target porque ahora el servidor Express 
    # maneja el prefijo /tickets directamente.
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /tickets
        pathType: Prefix
        backend:
          service:
            name: support-app-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: support-app-service
            port:
              number: 80